spring:
  application:
    name: ojtProject
  profiles:
    active: local
  messages:
    basename: errors

  datasource:
    url: jdbc:mariadb://localhost:3306/dbOjtProject
    username: root
    password: jhlee

mybatis:
  type-aliases-package: com.ojt.first_be.domain
